// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package com.kingigame.ussdpayment.models;

public final class Ping {
  private Ping() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BINPingRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 disconectTime = 1;
    /**
     * <code>optional int32 disconectTime = 1;</code>
     */
    boolean hasDisconectTime();
    /**
     * <code>optional int32 disconectTime = 1;</code>
     */
    int getDisconectTime();
  }
  /**
   * Protobuf type {@code BINPingRequest}
   */
  public static final class BINPingRequest extends
      com.google.protobuf.GeneratedMessage
      implements BINPingRequestOrBuilder {
    // Use BINPingRequest.newBuilder() to construct.
    private BINPingRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BINPingRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BINPingRequest defaultInstance;
    public static BINPingRequest getDefaultInstance() {
      return defaultInstance;
    }

    public BINPingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BINPingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              disconectTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kingigame.ussdpayment.models.Ping.BINPingRequest.class, com.kingigame.ussdpayment.models.Ping.BINPingRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<BINPingRequest> PARSER =
        new com.google.protobuf.AbstractParser<BINPingRequest>() {
      public BINPingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BINPingRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BINPingRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 disconectTime = 1;
    public static final int DISCONECTTIME_FIELD_NUMBER = 1;
    private int disconectTime_;
    /**
     * <code>optional int32 disconectTime = 1;</code>
     */
    public boolean hasDisconectTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 disconectTime = 1;</code>
     */
    public int getDisconectTime() {
      return disconectTime_;
    }

    private void initFields() {
      disconectTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, disconectTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, disconectTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kingigame.ussdpayment.models.Ping.BINPingRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BINPingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kingigame.ussdpayment.models.Ping.BINPingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kingigame.ussdpayment.models.Ping.BINPingRequest.class, com.kingigame.ussdpayment.models.Ping.BINPingRequest.Builder.class);
      }

      // Construct using com.kingigame.ussdpayment.models.Ping.BINPingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        disconectTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingRequest_descriptor;
      }

      public com.kingigame.ussdpayment.models.Ping.BINPingRequest getDefaultInstanceForType() {
        return com.kingigame.ussdpayment.models.Ping.BINPingRequest.getDefaultInstance();
      }

      public com.kingigame.ussdpayment.models.Ping.BINPingRequest build() {
        com.kingigame.ussdpayment.models.Ping.BINPingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kingigame.ussdpayment.models.Ping.BINPingRequest buildPartial() {
        com.kingigame.ussdpayment.models.Ping.BINPingRequest result = new com.kingigame.ussdpayment.models.Ping.BINPingRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.disconectTime_ = disconectTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kingigame.ussdpayment.models.Ping.BINPingRequest) {
          return mergeFrom((com.kingigame.ussdpayment.models.Ping.BINPingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kingigame.ussdpayment.models.Ping.BINPingRequest other) {
        if (other == com.kingigame.ussdpayment.models.Ping.BINPingRequest.getDefaultInstance()) return this;
        if (other.hasDisconectTime()) {
          setDisconectTime(other.getDisconectTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kingigame.ussdpayment.models.Ping.BINPingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kingigame.ussdpayment.models.Ping.BINPingRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 disconectTime = 1;
      private int disconectTime_ ;
      /**
       * <code>optional int32 disconectTime = 1;</code>
       */
      public boolean hasDisconectTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 disconectTime = 1;</code>
       */
      public int getDisconectTime() {
        return disconectTime_;
      }
      /**
       * <code>optional int32 disconectTime = 1;</code>
       */
      public Builder setDisconectTime(int value) {
        bitField0_ |= 0x00000001;
        disconectTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 disconectTime = 1;</code>
       */
      public Builder clearDisconectTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        disconectTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BINPingRequest)
    }

    static {
      defaultInstance = new BINPingRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BINPingRequest)
  }

  public interface BINPingResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool responseCode = 1;
    /**
     * <code>required bool responseCode = 1;</code>
     */
    boolean hasResponseCode();
    /**
     * <code>required bool responseCode = 1;</code>
     */
    boolean getResponseCode();

    // optional string message = 2;
    /**
     * <code>optional string message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    // optional bool disconnect = 3;
    /**
     * <code>optional bool disconnect = 3;</code>
     */
    boolean hasDisconnect();
    /**
     * <code>optional bool disconnect = 3;</code>
     */
    boolean getDisconnect();
  }
  /**
   * Protobuf type {@code BINPingResponse}
   */
  public static final class BINPingResponse extends
      com.google.protobuf.GeneratedMessage
      implements BINPingResponseOrBuilder {
    // Use BINPingResponse.newBuilder() to construct.
    private BINPingResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BINPingResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BINPingResponse defaultInstance;
    public static BINPingResponse getDefaultInstance() {
      return defaultInstance;
    }

    public BINPingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BINPingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              responseCode_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              disconnect_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kingigame.ussdpayment.models.Ping.BINPingResponse.class, com.kingigame.ussdpayment.models.Ping.BINPingResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<BINPingResponse> PARSER =
        new com.google.protobuf.AbstractParser<BINPingResponse>() {
      public BINPingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BINPingResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BINPingResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool responseCode = 1;
    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private boolean responseCode_;
    /**
     * <code>required bool responseCode = 1;</code>
     */
    public boolean hasResponseCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool responseCode = 1;</code>
     */
    public boolean getResponseCode() {
      return responseCode_;
    }

    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool disconnect = 3;
    public static final int DISCONNECT_FIELD_NUMBER = 3;
    private boolean disconnect_;
    /**
     * <code>optional bool disconnect = 3;</code>
     */
    public boolean hasDisconnect() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool disconnect = 3;</code>
     */
    public boolean getDisconnect() {
      return disconnect_;
    }

    private void initFields() {
      responseCode_ = false;
      message_ = "";
      disconnect_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResponseCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, responseCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, disconnect_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, responseCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, disconnect_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kingigame.ussdpayment.models.Ping.BINPingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kingigame.ussdpayment.models.Ping.BINPingResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BINPingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kingigame.ussdpayment.models.Ping.BINPingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kingigame.ussdpayment.models.Ping.BINPingResponse.class, com.kingigame.ussdpayment.models.Ping.BINPingResponse.Builder.class);
      }

      // Construct using com.kingigame.ussdpayment.models.Ping.BINPingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        responseCode_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        disconnect_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kingigame.ussdpayment.models.Ping.internal_static_BINPingResponse_descriptor;
      }

      public com.kingigame.ussdpayment.models.Ping.BINPingResponse getDefaultInstanceForType() {
        return com.kingigame.ussdpayment.models.Ping.BINPingResponse.getDefaultInstance();
      }

      public com.kingigame.ussdpayment.models.Ping.BINPingResponse build() {
        com.kingigame.ussdpayment.models.Ping.BINPingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kingigame.ussdpayment.models.Ping.BINPingResponse buildPartial() {
        com.kingigame.ussdpayment.models.Ping.BINPingResponse result = new com.kingigame.ussdpayment.models.Ping.BINPingResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseCode_ = responseCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.disconnect_ = disconnect_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kingigame.ussdpayment.models.Ping.BINPingResponse) {
          return mergeFrom((com.kingigame.ussdpayment.models.Ping.BINPingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kingigame.ussdpayment.models.Ping.BINPingResponse other) {
        if (other == com.kingigame.ussdpayment.models.Ping.BINPingResponse.getDefaultInstance()) return this;
        if (other.hasResponseCode()) {
          setResponseCode(other.getResponseCode());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasDisconnect()) {
          setDisconnect(other.getDisconnect());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResponseCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kingigame.ussdpayment.models.Ping.BINPingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kingigame.ussdpayment.models.Ping.BINPingResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool responseCode = 1;
      private boolean responseCode_ ;
      /**
       * <code>required bool responseCode = 1;</code>
       */
      public boolean hasResponseCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool responseCode = 1;</code>
       */
      public boolean getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>required bool responseCode = 1;</code>
       */
      public Builder setResponseCode(boolean value) {
        bitField0_ |= 0x00000001;
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool responseCode = 1;</code>
       */
      public Builder clearResponseCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseCode_ = false;
        onChanged();
        return this;
      }

      // optional string message = 2;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      // optional bool disconnect = 3;
      private boolean disconnect_ ;
      /**
       * <code>optional bool disconnect = 3;</code>
       */
      public boolean hasDisconnect() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool disconnect = 3;</code>
       */
      public boolean getDisconnect() {
        return disconnect_;
      }
      /**
       * <code>optional bool disconnect = 3;</code>
       */
      public Builder setDisconnect(boolean value) {
        bitField0_ |= 0x00000004;
        disconnect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool disconnect = 3;</code>
       */
      public Builder clearDisconnect() {
        bitField0_ = (bitField0_ & ~0x00000004);
        disconnect_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BINPingResponse)
    }

    static {
      defaultInstance = new BINPingResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BINPingResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BINPingRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BINPingRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BINPingResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BINPingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nping.proto\"\'\n\016BINPingRequest\022\025\n\rdiscon" +
      "ectTime\030\001 \001(\005\"L\n\017BINPingResponse\022\024\n\014resp" +
      "onseCode\030\001 \002(\010\022\017\n\007message\030\002 \001(\t\022\022\n\ndisco" +
      "nnect\030\003 \001(\010B\"\n com.kingigame.ussdpayment" +
      ".models"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BINPingRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BINPingRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BINPingRequest_descriptor,
              new java.lang.String[] { "DisconectTime", });
          internal_static_BINPingResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BINPingResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BINPingResponse_descriptor,
              new java.lang.String[] { "ResponseCode", "Message", "Disconnect", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
